Add missing CMakeLists dependencies
This solution forces the code to build only after all the dependencies
have been built. This fixes the following error:

    sick_ldmrs_object_marker.cpp:38:41: fatal error: sick_ldmrs_msgs/ObjectArray.h: No such file or directory

To fix that error alone, the following would have been sufficient:

    add_dependencies(sick_ldmrs_object_marker sick_ldmrs_msgs_generate_messages_cpp)

... but then we would have to replicate that for all the msg packages.